Metrics/LineLength:
  Exclude:
    - spec/**/*
    - jekyll-seo-tag.gemspec

Style/Documentation:
  Enabled: false

Style/FileName:
  Enabled: false

Metrics/AbcSize:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/PerceivedComplexity:
  Enabled: false
